# Generated by Django 2.2.6 on 2019-10-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceMash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='facemash_photos')),
                ('ratings', models.FloatField(default=1500)),
                ('rd', models.FloatField(default=350)),
                ('sigma', models.FloatField(default=0.06)),
            ],
            options={
                'verbose_name_plural': 'Facemash',
            },
        ),
    ]
